name: Message Sender
description: Facilitates sending slack messages
inputs:
  channel:
    required: true
    description: Slack channel to send message to
  fail_on_error:
    required: false
    default: 'false'
    description: Used to mark the action as failed if an error occurs.
  include_workflow_status:
    required: false
    default: 'false'
    description: Includes the overall workflow conclusion and status of individual jobs.
  footer_icon:
    required: false
    default: 'https://slack.github.com/static/img/favicon-neutral.png'
    description: A valid URL to an image that will be displayed beside the footer.
  ignore_actions:
    required: false
    default: ''
    description: Processing will be ignored for any actions listed.
  skip_bots:
    required: false
    default: 'true'
    description: Processing will be skipped for bot actors.

runs:
  using: node20
  main: invoke-binary.js
